const GEONAMES_USERNAME = process.env.GEONAMES_USERNAME;
const WEATHERBIT_APIKEY = process.env.WEATHERBIT_APIKEY;
const PIXABAY_APIKEY = process.env.PIXABAY_APIKEY;

export { GEONAMES_USERNAME, WEATHERBIT_APIKEY, PIXABAY_APIKEY };
